### PR TITLE
fix: Hide line-limit indicator in comments

### LINKED ISSUE #326: [Bug] line limit line over comments
With the newly added line limit, it draws the column line over file comments:
image

also draws over inline comments but only within the padding:
image

### PR DESCRIPTION
**Pull request by BenWildeman**
-   [ ] I updated the CHANGELOG.md
-   [x] I tested the changes in this pull request myself
-   [ ] I added Automated Tests
-   [ ] I added an Option to enable / disable this feature
-   [ ] I updated the README.md, with pictures if necessary

---

### CODE REVIEW

File: src/limit-line-length/limit-line-length.js [hunk 1]
```diff
@@ -8,6 +8,10 @@ function createCssRules(lineLengthLimit, isStickyHeaderEnabled) {
     }
 
     let cssRules = `
+        .refract-content-container, .comment-thread-container {
```
Comment (BenWildeman) [inline src/limit-line-length/limit-line-length.js:11]: `.refract-content-container` stops line from being above file comment thread

`.comment-thread-container` stops line from being within the padding of a line comment thread

**Review by reyronald — APPROVED** [review]
Thanks a lot!
