### PR TITLE
Firefox performance improved with highlight feature

### LINKED ISSUE #266: Firefox: 'A script in the extension "Refined Bitbucket" is causing Firefox to slow down'
First of all: I'm not an expert with the Firefox developer tools, so if I'm missing something which could give you a lot more information, please do tell!

I'm on Firefox (64.0) on Mac (10.14.2) with Refined Bitbucket (3.14.1), all the latest versions. The following error message appears on every single pull request that I try to view:

> image

No amount of waiting seems to help. I have tried 
* disabling all other addons
* opening the developer tools, but the slowdown is so intense that only the network tab is non-blank

… but to no avail.

The slowdown occurs after the initial render of the page. The list of diffs is shown, but the «Load all failed diffs» button is not. My guess is that the block occurs during some initial try at loading all diffs.

Could someone affirm that this is not just my problem? Going to any PR using Firefox with Refined Bitbucket (preferably on a Mac) should do it.  

If it turns out to not just be my problem, I'd be glad to help with further debugging and possibly solving.

### LINKED ISSUE #348: Firefox says: Script is not responding
Hello,

Firefox 75.0 always says that the [script is not responding](https://support.mozilla.org/de/kb/warnung-nicht-antwortendes-skript#w_other-causes) on a Bitbucket pull request, with only 8 files:

2020-04-22 10_14_10-logima _ DoseHub _ Pull request #60_ IHUB-267 Enabled automatic publish on Insta

The two big files are autocollapsed. 

What information do you need to check this problem?

Add-On Version: 3.20.0

Regards!
   Stefan

### LINKED ISSUE #351: Refined Bitbucket is causing Firefox to slow down
Hi, 

For a while now (about two months) I've been having issues with Refined Bitbucket. Whenever I enter PRs, a browser's bar appears informing me that 

image

Only stopping it or temporarily disabling helps - waiting doesn't.

The issue is present no matter the PR, if it has many files or just a few, a long ones or one-liners. 

Please let me know if you need any further info from me to look into this. 

Refined Bitbucket version: 3.20.0.
Firefox: up-to-date, right now 75.0.

### PR DESCRIPTION
**Pull request by jwallet**
I got the same issue as the issues mentionned here, I did not added my build index.js at this time in Options - Collapsable files / Delete files. So highlighter was trying to colorize 6 minified lines:
- x2  - 16,631 (these were actually taking 1sec each)
- x2 ~281,000
- x2  ~327,000 

the last 4 were causing the script to crash, they resolved after 9secs each, but even then firefox was not responding, just scrolling up and down, I had to kill the tab after some minutes to kill Prism from keep trying to highlight the whole lines

### firefox performance improvements
- autocollapse: run it first and return if successful to kill the propagation because it won't be rendered anyway, just like delete does.
- highligther: added promises when executing prism.highlightElement
- highlighter: lines over the arbitrary max length of 9999 will be considered as minified and ignored
- Prism: Updated prism form 1.15 to 1.20, I took the previous url from 1.15 to make sure I got the same addons and features from 1.15
- Updated syntax second try logic (related to `<add>` `<del>` tags)

### some tweak for diff selector
- Now logs the element in `console.error `
- `new Set` for selectors to make sure no duplicates are there
- Valid if the element from the selector is `aria-hidden` or `display:none`

close #348 
close #351 
close #266 

-   [ ] I updated the CHANGELOG.md
-   [x] I tested the changes in this pull request myself
-   [ ] I added Automated Tests
-   [ ] I added an Option to enable / disable this feature
-   [ ] I updated the README.md, with pictures if necessary

---

### CODE REVIEW

File: src/main.js [hunk 1]
```diff
@@ -178,31 +178,44 @@ function codeReviewFeatures(config) {
...
-                }
-            } catch (error) {
-                // Something went wrong
-                console.error('refined-bitbucket(code-review): ', error)
+        try {
+            if (this.matches(summarySelectors.join(', '))) {
+                manipulateSummary(this)
             }
+
+            if (this.matches(diffSelector)) {
```
Comment (jwallet) [inline src/main.js:207]: looking for parent `diff` just to make sure it gets validated for `display:none` before running functions.

**Comment by reyronald** [comment]
I can't reproduce this bug in the `dev` branch 😕 . I tried creating a PR while having all extension's options enabled, and with both the new UI and old UI experience.

Can you think of what might be different in your environment versus mine? I'd like to be able to reproduce this locally to be able to properly review the PR

**Comment by jwallet** [comment]
using firefox and old experience, looks like the element target can be reached if the pr is small, when is bigger, some elements gets removed (diff tab) by bitbucket when in the commit tab. this does happen when developping, firefox has some memory management issues when reloading, it cannot remove unused memory correctly, resulting in unmanaged memory. and the webpage gets slow and the error pops, at this time, firefox takes around 6gb ram space. so maybe an issue when the selector is triggered at the same time it gets removed by the DOM. Slow computers might have the same issue.

I can't reproduce this bug as well, this morning, but I remember it was coming from `<section>` blocks. I will try to find the proper path to test it

File: src/main.js [hunk 2]
```diff
@@ -178,31 +180,40 @@ function codeReviewFeatures(config) {
...
 
-    const summarySelectors =
-        '#compare-diff-content, #pr-tab-content, #commit, #diff'
+    const summarySelectors = [
+        '#compare-diff-content',
+        '#pr-tab-content',
+        '#commit',
+        '#diff',
+    ]
     const diffSelector = 'section.bb-udiff'
```
Comment (jwallet) [inline src/main.js:193]: added back the previous selector but kept validation hidden/visible line 197:202

File: src/syntax-highlight/syntax-highlight.js [hunk 3]
```diff
@@ -39,7 +39,7 @@ export default function syntaxHighlight(diff, afterWordDiff) {
     }
 
     const $diff = $(diff)
-    syntaxHighlightSourceCodeLines($diff)
+    // syntaxHighlightSourceCodeLines($diff)
```
Comment (jwallet) [inline src/syntax-highlight/syntax-highlight.js:42]: i commented to know why we started the process and reapplied it later with afterWordDiff callback, it was another reason of performance issue, some lines lost their token/color syntax after the second highlight

Comment (jwallet) [reply src/syntax-highlight/syntax-highlight.js:42]: 2 tests are currently failing because i commented this line, so depends on the answer I will change the tests

File: src/syntax-highlight/syntax-highlight.js [hunk 4]
```diff
@@ -39,10 +39,10 @@ export default function syntaxHighlight(diff, afterWordDiff) {
     }
 
     const $diff = $(diff)
-    syntaxHighlightSourceCodeLines($diff)
+    syntaxHighlightSourceCodeLines($diff, 'pre.source:not([class*=language])')
```
Comment (jwallet) [inline src/syntax-highlight/syntax-highlight.js:46]: first time we highlight we never have class language

File: src/syntax-highlight/syntax-highlight.js [hunk 5]
```diff
@@ -39,10 +39,10 @@ export default function syntaxHighlight(diff, afterWordDiff) {
...
 
     afterWordDiff(() => {
-        syntaxHighlightSourceCodeLines($diff)
+        syntaxHighlightSourceCodeLines($diff, '.addition pre, .deletion pre')
```
Comment (jwallet) [inline src/syntax-highlight/syntax-highlight.js:48]: second time, we will want to look for tags `pre:has(ins)` `pre:has(del)` but the word-diff block only have `<ins>` elements in the `addition` block, the `deletion` block will be re-rendered as well, so we have to re-highlight there too. so the selector is `.addition pre, .deletion pre` and anyway the mutation-observer will not ask to re-render a diff block that as no word-diff ins/del

File: src/syntax-highlight/syntax-highlight.js [hunk 6]
```diff
@@ -69,19 +69,38 @@ export default function syntaxHighlight(diff, afterWordDiff) {
...
-    })
+async function syntaxHighlightSourceCodeLines($diff, querySelector) {
+    const sourceLines = [...$diff.find(querySelector)]
+
+    const promises = sourceLines.map(
+        preElement =>
+            new Promise((resolve, reject) => {
+                const { classList, firstChild, innerText } = preElement
+                if (
+                    firstChild.$$rbb_isSyntaxHighlighted &&
```
Comment (jwallet) [inline src/syntax-highlight/syntax-highlight.js:81]: went bitbucket re-renders a line with word-diff it changes the content, it leaves the class and property there, so I check for childElementCount (tokens) to see if it's just plain text or it was highlighted

File: src/syntax-highlight/syntax-highlight.js (hunk 5 above)
Comment (jwallet) [reply src/syntax-highlight/syntax-highlight.js:48]: image

File: src/syntax-highlight/syntax-highlight.js [hunk 7]
```diff
@@ -69,19 +69,36 @@ export default function syntaxHighlight(diff, afterWordDiff) {
...
+                    return
+                }
+
+                // Lines over the arbitrary max length of 9999 will be considered as minified
+                if (innerText && innerText.length > 9999) {
+                    reject(`Line is too long, probably minified`)
+                    return
+                }
+
+                Prism.highlightElement(preElement)
```
Comment (jwallet) [inline src/syntax-highlight/syntax-highlight.js:94]: Maybe we can use web worker, but Prism warn about using async highlight... web workers are slower and just limiting the text to a max length of 9999 is quite enough. Sure it will skip this line, but the ui does not freezes anymore

```jsx
Prims.highlightElement(element, true, () => {}); // async with web worker
```

File: src/syntax-highlight/syntax-highlight.js [hunk 8]
```diff
@@ -69,19 +72,36 @@ export default function syntaxHighlight(diff, afterWordDiff) {
...
+async function syntaxHighlightSourceCodeLines($diff, querySelector) {
+    const sourceLines = [...$diff.find(querySelector)]
+
+    const promises = sourceLines.map(
+        preElement =>
+            new Promise((resolve, reject) => {
+                const { classList, firstChild, innerText } = preElement
+
+                if (firstChild.$$rbb_isSyntaxHighlighted) {
+                    reject(new Error('Already highlighted'))
```
Comment (reyronald) [inline src/syntax-highlight/syntax-highlight.js:84]: Do we have to reject with an Error here? Can't we just ignore this line, resolve, and skip to the next promise? Worried that we will polluting the console and stack with unhandled exceptions that are unactionable and don't really represent an error conceptually

**Review by reyronald — COMMENTED** [review]
Looks good to me! 

I'll be merging this by Monday, would like to wait to see if you can answer the question I left before then.

Thanks a lot for working on this as usual 🙏

**Review by reyronald — APPROVED** [review]

File: src/syntax-highlight/syntax-highlight.js (hunk 8 above)
Comment (jwallet) [reply src/syntax-highlight/syntax-highlight.js:84]: no no need to add an error. you can just reject. sorry I lately left github for other stuff I do not think I will give more time to projects outside of those I am maintening.

Comment (reyronald) [reply src/syntax-highlight/syntax-highlight.js:84]: No problem @jwallet ! Thanks a lot for all you've contributed so far! Greatly appreciated ♥
